### PR TITLE
Update ditados with Cavalo dado não se olha os dentes

### PR DESCRIPTION
**Pull request by anontyro**

### CODE REVIEW

**Comment by antonioalmeida** [comment]
Hi @anontyro , thank you for contributing. 

While "queimar as pestanas" is a fairly common expression, I believe it fits into the "slang" category, not really a ditado.

**Comment by anontyro** [comment]
ok i'll try another one then 👍

**Comment by anontyro** [comment]
Ok got a new one let me know if this fits better, thanks!

**Comment by antonioalmeida** [comment]
The content is fine, but the JSON is not formatted properly. Can you please fix it?

**Comment by anontyro** [comment]
@antonioalmeida fixed the issue should be good now sorry about that

**Pull request merged**
