### PR TITLE
create ditado

### PR DESCRIPTION
**Pull request by LuizHAP**

### CODE REVIEW

**Comment by LuizHAP** [comment]
@antonioalmeida please, dont forget to apply hacktoberfest-accepted label

**Comment by antonioalmeida** [comment]
@LuizHAP please don't reformat the entries by adding whitespace. Fix that and I'll accept the PR.

Also, the repository is tagged with `hacktoberfest` so I don't need to add the `hacktoberfest-accepted` to each PR

**Comment by LuizHAP** [comment]
@antonioalmeida fixed, sorry, it was a change to the eslint

**Comment by antonioalmeida** [comment]
@LuizHAP I'm sorry but your PR is registering a lot of unnecessary changes (take a look at the diff). For consistency, I ask to redo your changes from scratch. The easiest would be to just start over with a new PR

**Pull request closed without merging**
