### PR TITLE
add my ditado

### PR DESCRIPTION
**Pull request by touhidulShawan**
Add 2 new ditado

### CODE REVIEW

**Comment by antonioalmeida** [comment]
Hi @touhidulShawan , thank you for contributing.

While your contribution is perfect, the point of this repository is to collect _portuguese_ ditados, not English based ones. Do you think you can replace those?

**Comment by touhidulShawan** [comment]
yes can be replaced

**Comment by touhidulShawan** [comment]
Updated to Portuguese

**Comment by antonioalmeida** [comment]
Sorry @touhidulShawan, but simply translating English proverbs to Portuguese does not work. _Ditados_, or any popular phrase in a given language only works with its exact wording.

[Here](http://www.fraseseproverbios.com/proverbios-portugueses.php) is a small list of _ditados_, but without their meaning. I can help with that later 😄

**Comment by touhidulShawan** [comment]
It`s okay. I understand. Actually, I do not know portuguse, so I think I was not able to help you

**Pull request closed without merging**
